name: video_watermark
description: Simple Flutter package to add image as overlay in the video along with video trim option.
homepage: https://www.eded.in/video_watermark
repository: https://github.com/EDEDIN-Solutions/video_watermark
publish_to: none

version: 1.0.5

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/anonfaded/ffmpeg-kit
      path: flutter/flutter
  path_provider: ^2.0.11

platforms:
  android:
  ios:
